In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.h1 = nn.Linear(5,5)
        self.h2 = nn.Linear(5,1)
    
    def forward(self, x):
        x = F.relu(self.h1(x))
        return self.h2(x)

In [65]:
mod1 = Test()
mod2 = Test()

In [33]:
l1 = nn.Linear(3, 5)
l2 = nn.Linear(3, 5)

x = torch.tensor([[0.6, 0.4],[0.3, 0.7],[0.2, 0.8]], requires_grad=True)
y = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], requires_grad=True)

z1 = l1(y)
z2 = l2(y)
print(x)
print(z1)
print(z2)

first = torch.tensor([0])
second = torch.tensor([1])
z = z1*torch.index_select(x, 1, first) + z2*torch.index_select(x, 1, second)
print(z.sum())
z.sum().backward()

tensor([[ 0.6000,  0.4000],
        [ 0.3000,  0.7000],
        [ 0.2000,  0.8000]])
tensor([[-1.8242, -0.0850, -0.1801, -0.9286,  0.4447],
        [-4.4703, -0.4751,  0.6109, -2.5957,  0.0156],
        [-7.1164, -0.8652,  1.4019, -4.2628, -0.4134]])
tensor([[ 1.1442,  1.5508,  0.9714,  0.5034, -1.1375],
        [ 3.4194,  2.9158,  1.8290,  1.6890, -2.5635],
        [ 5.6947,  4.2807,  2.6866,  2.8745, -3.9896]])
tensor(9.6836)


In [35]:
print(x.grad)
print(first.grad)

tensor([[ -2.5733,   3.0324],
        [ -6.9146,   7.2896],
        [-11.2559,  11.5469]])
None
