In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.h1 = nn.Linear(5,5)
        self.h2 = nn.Linear(5,1)
    
    def forward(self, x):
        x = F.relu(self.h1(x))
        return self.h2(x)

In [65]:
mod1 = Test()
mod2 = Test()

In [66]:
m1 = mod1.state_dict()
m2 = mod2.state_dict()
print(m1['h1.bias'])
print(m2['h1.bias'])

tensor([-0.0240, -0.4443,  0.2072, -0.0605,  0.2674])
tensor([ 0.3853, -0.1554, -0.0690,  0.0083,  0.2623])


In [67]:
mod3 = Test()
print(mod3.state_dict()['h1.bias'])

tensor([ 0.1609, -0.2682, -0.2873,  0.2245,  0.3853])


In [68]:
for name, param in mod3.named_parameters():
    param.data = m1[name].data.clone()

In [69]:
print(mod3.state_dict()['h1.bias'])

tensor([-0.0240, -0.4443,  0.2072, -0.0605,  0.2674])


In [70]:
m1['h1.bias'].data.fill_(1)

tensor([ 1.,  1.,  1.,  1.,  1.])

In [71]:
print(m1['h1.bias'])
print(mod3.state_dict()['h1.bias'])

tensor([ 1.,  1.,  1.,  1.,  1.])
tensor([-0.0240, -0.4443,  0.2072, -0.0605,  0.2674])


In [73]:
x = torch.Tensor([1, 2, 3, 4, 5])
out = mod3(x)
print(out)
out.backward()

tensor([ 0.3814])


In [78]:
for name, param in mod3.named_parameters():
    print(name, param.grad)

h1.weight tensor([[-0.0973, -0.1946, -0.2920, -0.3893, -0.4866],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0564,  0.1128,  0.1692,  0.2256,  0.2820],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])
h1.bias tensor(1.00000e-02 *
       [-9.7323,  0.0000,  0.0000,  5.6394,  0.0000])
h2.weight tensor([[ 0.0439,  0.0000,  0.0000,  0.7734,  0.0000]])
h2.bias tensor([ 1.])


In [80]:
out = mod1(x)
print(out)
out.backward()
for name, param in mod1.named_parameters():
    print(name, param.grad)

tensor([ 0.4112])
h1.weight tensor([[-0.0973, -0.1946, -0.2920, -0.3893, -0.4866],
        [-0.0027, -0.0054, -0.0082, -0.0109, -0.0136],
        [ 0.1111,  0.2221,  0.3332,  0.4443,  0.5553],
        [ 0.0564,  0.1128,  0.1692,  0.2256,  0.2820],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])
h1.bias tensor([-0.0973, -0.0027,  0.1111,  0.0564,  0.0000])
h2.weight tensor([[ 1.0679,  0.5692,  0.6411,  1.8339,  0.0000]])
h2.bias tensor([ 1.])


In [4]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[7],[8]])

In [5]:
for a, b in zip(x,y):
    print(a, b)

tensor([ 1.,  2.,  3.]) tensor([ 7.])
tensor([ 4.,  5.,  6.]) tensor([ 8.])


In [92]:
torch.stack([x[0] for _ in range(3)], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]])