In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.h1 = nn.Linear(5,5)
        self.h2 = nn.Linear(5,1)
    
    def forward(self, x):
        x = F.relu(self.h1(x))
        return self.h2(x)

In [65]:
mod1 = Test()
mod2 = Test()

In [3]:
l1 = nn.Linear(3, 5)
l2 = nn.Linear(3, 5)

x = torch.tensor([[0.6, 0.4],[0.3, 0.7],[0.2, 0.8]], requires_grad=True)
y = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], requires_grad=True)

z1 = l1(y)
z2 = l2(y)
print(x)
print(z1)
print(z2)

first = torch.tensor([0])
second = torch.tensor([1])
z = z1*torch.index_select(x, 1, first) + z2*torch.index_select(x, 1, second)
print(z.sum())
z.sum().backward()

tensor([[ 0.6000,  0.4000],
        [ 0.3000,  0.7000],
        [ 0.2000,  0.8000]])
tensor([[-2.0167, -0.5384,  0.0043,  0.4240, -1.9677],
        [-3.4131, -0.9322, -1.0302,  2.4787, -2.9286],
        [-4.8095, -1.3259, -2.0647,  4.5334, -3.8895]])
tensor([[ 0.8857, -1.1850, -2.3944,  0.1306, -0.7181],
        [ 0.6081, -2.2359, -5.9999, -0.1207, -1.5946],
        [ 0.3305, -3.2869, -9.6055, -0.3721, -2.4711]])
tensor(-25.8922)


In [10]:
print(l1.weight.requires_grad)
print(l1.weight.data)
l1.weight.data = torch.rand(5,3)
print(l1.weight.data)
print(l1.weight.requires_grad)


True
tensor([[ 0.9585,  0.2135,  0.6790],
        [ 0.8157,  0.5842,  0.4499],
        [ 0.0863,  0.4487,  0.6572],
        [ 0.5162,  0.6354,  0.2955],
        [ 0.0762,  0.8673,  0.3155]])
tensor([[ 0.2038,  0.6811,  0.1129],
        [ 0.7391,  0.1135,  0.0312],
        [ 0.3935,  0.6664,  0.0331],
        [ 0.9617,  0.5869,  0.8342],
        [ 0.7716,  0.6710,  0.8751]])
True
